import isCPF from '@/utils/cpf'
import isCNPJ from '@/utils/cnpj'

export const getTipoChavePix = (chave: string): string => {
  //tiposPix = ['CPF','CNPJ','Email','Celular','Chave aleatória']
  let strTeste = chave.replace(/\D/g, '') // apenas numeros

  if (strTeste.match(/^[0-9]{11}$/) && isCPF(strTeste)) return 'CPF'
  if (strTeste.match(/^[0-9]{11}$/)) return 'Celular'
  if (strTeste.match(/^[0-9]{14}$/) && isCNPJ(strTeste)) return 'CNPJ'

  strTeste = chave //chave.replace(/\s/g,'') // tira os espaços
  if (strTeste.match(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/)) return 'Email'

  strTeste = chave.replace(/[^a-f0-9]/g, '') // tira os espaços
  if (strTeste.match(/[0-9a-f]{8}[0-9a-f]{4}[0-9a-f]{4}[0-9a-f]{4}[0-9a-f]{12}/)) return 'Random'

  return ''
}

export const bancoList = [
  { key: '356', value: 'ABN AMRO' },
  { key: '332', value: 'Acesso Soluções de Pagamento' },
  { key: '246', value: 'BANCO ABC ROMA' },
  { key: '222', value: 'BANCO AGF BRASIL' },
  { key: '483', value: 'BANCO AGRIMISA' },
  { key: '217', value: 'BANCO AGROINVEST' },
  { key: '654', value: 'BANCO AJ RENNER' },
  { key: '025', value: 'BANCO ALFA' },
  { key: '215', value: 'BANCO AMERICA DO SUL' },
  { key: '621', value: 'BANCO APLICAP' },
  { key: '625', value: 'BANCO ARAUCARIA' },
  { key: '213', value: 'BANCO ARBI' },
  { key: '648', value: 'BANCO ATLANTIS' },
  { key: '201', value: 'BANCO AUGUSTA INDUSTRIA E COMERCIAL' },
  { key: '394', value: 'BANCO BMC' },
  { key: '318', value: 'BANCO BMG' },
  { key: '116', value: 'BANCO BNL DO BRASIL' },
  { key: '399', value: 'BANCO BAMERINDUS DO BRASIL' },
  { key: '239', value: 'BANCO BANCRED' },
  { key: '230', value: 'BANCO BANDEIRANTES' },
  { key: '752', value: 'BANCO BANQUE NATIONALE DE PARIS' },
  { key: '107', value: 'BANCO BBM' },
  { key: '267', value: 'BANCO BBM-COM.C.IMOB.CFI' },
  { key: '231', value: 'BANCO BOAVISTA' },
  { key: '262', value: 'BANCO BOREAL' },
  { key: '351', value: 'BANCO BOZANO SIMONSEN' },
  { key: '237', value: 'BANCO BRADESCO' },
  { key: '225', value: 'BANCO BRASCAN' },
  { key: '282', value: 'BANCO BRASILEIRO COMERCIAL' },
  { key: '501', value: 'BANCO BRASILEIRO IRAQUIANO' },
  { key: '168', value: 'BANCO CCF BRASIL' },
  { key: '336', value: 'BANCO C6' },
  { key: '263', value: 'BANCO CACIQUE' },
  { key: '236', value: 'BANCO CAMBIAL' },
  { key: '266', value: 'BANCO CEDULA' },
  { key: '002', value: 'BANCO CENTRAL DO BRASIL' },
  { key: '244', value: 'BANCO CIDADE' },
  { key: '713', value: 'BANCO CINDAM' },
  { key: '241', value: 'BANCO CLASSICO' },
  { key: '308', value: 'BANCO COMERCIAL BANCESA' },
  { key: '730', value: 'BANCO COMERCIAL PARAGUAYO' },
  { key: '753', value: 'BANCO COMERCIAL URUGUAI' },
  { key: '756', value: 'BANCO COOPERATIVO DO BRASIL' },
  { key: '109', value: 'BANCO CREDIBANCO' },
  { key: '721', value: 'BANCO CREDIBEL' },
  { key: '295', value: 'BANCO CREDIPLAN' },
  { key: '220', value: 'BANCO CREFISUL' },
  { key: '628', value: 'BANCO CRITERIUM' },
  { key: '229', value: 'BANCO CRUZEIRO' },
  { key: '003', value: 'BANCO DA AMAZONIA' },
  { key: '707', value: 'BANCO DAYCOVAL' },
  { key: '479', value: 'BANCO DE BOSTON' },
  { key: '070', value: 'BANCO DE BRASILIA' },
  { key: '219', value: 'BANCO DE CREDITO DE SAO PAULO' },
  { key: '640', value: 'BANCO DE CREDITO METROPOLITANO' },
  { key: '291', value: 'BANCO DE CREDITO NACIONAL' },
  { key: '022', value: 'BANCO DE CREDITO REAL DE MINAS GERAIS' },
  { key: '240', value: 'BANCO DE CREDITO REAL DE MINAS GERAIS' },
  { key: '300', value: 'BANCO DE LA NACION ARGENTINA' },
  { key: '627', value: 'BANCO DESTAK' },
  { key: '214', value: 'BANCO DIBENS' },
  { key: '649', value: 'BANCO DIMENSAO' },
  { key: '001', value: 'BANCO DO BRASIL' },
  { key: '034', value: 'BANCO DO ESADO DO AMAZONAS' },
  { key: '028', value: 'BANCO DO ESTADO DA BAHIA' },
  { key: '030', value: 'BANCO DO ESTADO DA PARAIBA' },
  { key: '020', value: 'BANCO DO ESTADO DE ALAGOAS' },
  { key: '031', value: 'BANCO DO ESTADO DE GOIAS' },
  { key: '048', value: 'BANCO DO ESTADO DE MINAS GERAIS' },
  { key: '024', value: 'BANCO DO ESTADO DE PERNAMBUCO' },
  { key: '059', value: 'BANCO DO ESTADO DE RONDONIA' },
  { key: '645', value: 'BANCO DO ESTADO DE RORAIMA' },
  { key: '027', value: 'BANCO DO ESTADO DE SANTA CATARINA' },
  { key: '047', value: 'BANCO DO ESTADO DE SERGIPE' },
  { key: '026', value: 'BANCO DO ESTADO DO ACRE' },
  { key: '635', value: 'BANCO DO ESTADO DO AMAPA' },
  { key: '035', value: 'BANCO DO ESTADO DO CEARA' },
  { key: '021', value: 'BANCO DO ESTADO DO ESPIRITO SANTO' },
  { key: '036', value: 'BANCO DO ESTADO DO MARANHAO' },
  { key: '032', value: 'BANCO DO ESTADO DO MATO GROSSO' },
  { key: '037', value: 'BANCO DO ESTADO DO PARA' },
  { key: '038', value: 'BANCO DO ESTADO DO PARANA' },
  { key: '039', value: 'BANCO DO ESTADO DO PIAUI' },
  { key: '029', value: 'BANCO DO ESTADO DO RIO DE JANEIRO' },
  { key: '041', value: 'BANCO DO ESTADO DO RIO GRANDE DO SUL' },
  { key: '004', value: 'BANCO DO NORDESTE DO BRASIL' },
  { key: '302', value: 'BANCO DO PROGRESSO' },
  { key: '622', value: 'BANCO DRACMA' },
  { key: '743', value: 'BANCO EMBLEMA' },
  { key: '245', value: 'BANCO EMPRESARIAL' },
  { key: '242', value: 'BANCO EUROINVEST' },
  { key: '641', value: 'BANCO EXCEL ECONOMICO' },
  { key: '496', value: 'BANCO EXTERIOR DE ESPANA' },
  { key: '265', value: 'BANCO FATOR' },
  { key: '375', value: 'BANCO FENICIA' },
  { key: '224', value: 'BANCO FIBRA' },
  { key: '626', value: 'BANCO FICSA' },
  { key: '725', value: 'BANCO FINABANCO' },
  { key: '252', value: 'BANCO FININVEST' },
  { key: '728', value: 'BANCO FITAL' },
  { key: '729', value: 'BANCO FONTE' },
  { key: '434', value: 'BANCO FORTALEZA' },
  { key: '200', value: 'BANCO FRICRISA AXELRUD' },
  { key: '505', value: 'BANCO GARANTIA' },
  { key: '624', value: 'BANCO GENERAL MOTORS' },
  { key: '353', value: 'BANCO GERAL DO COMERCIO' },
  { key: '734', value: 'BANCO GERDAU' },
  { key: '731', value: 'BANCO GNPP' },
  { key: '221', value: 'BANCO GRAPHUS' },
  { key: '612', value: 'BANCO GUANABARA' },
  { key: '256', value: 'BANCO GULVINVEST' },
  { key: '303', value: 'BANCO HNF' },
  { key: '228', value: 'BANCO ICATU' },
  { key: '258', value: 'BANCO INDUSCRED' },
  { key: '604', value: 'BANCO INDUSTRIAL DO BRASIL' },
  { key: '320', value: 'BANCO INDUSTRIAL E COMERCIAL' },
  { key: '653', value: 'BANCO INDUSVAL' },
  { key: '077', value: 'BANCO INTER' },
  { key: '166', value: 'BANCO INTER-ATLANTICO' },
  { key: '630', value: 'BANCO INTERCAP' },
  { key: '722', value: 'BANCO INTERIOR DE SAO PAULO' },
  { key: '616', value: 'BANCO INTERPACIFICO' },
  { key: '232', value: 'BANCO INTERPART' },
  { key: '223', value: 'BANCO INTERUNION' },
  { key: '705', value: 'BANCO INVESTCORP' },
  { key: '249', value: 'BANCO INVESTCRED' },
  { key: '617', value: 'BANCO INVESTOR' },
  { key: '499', value: 'BANCO IOCHPE' },
  { key: '106', value: 'BANCO ITABANCO' },
  { key: '372', value: 'BANCO ITAMARATI' },
  { key: '341', value: 'BANCO ITAU' },
  { key: '488', value: 'BANCO JP MORGAN' },
  { key: '757', value: 'BANCO KEB DO BRASIL' },
  { key: '495', value: 'BANCO LA PROVINCIA DE BUENOS AIRES' },
  { key: '494', value: 'BANCO LA REP. ORIENTAL DEL URUGUAY' },
  { key: '234', value: 'BANCO LAVRA .' },
  { key: '235', value: 'BANCO LIBERAL' },
  { key: '600', value: 'BANCO LUSO BRASILEIRO' },
  { key: '233', value: 'BANCO MAPPIN' },
  { key: '647', value: 'BANCO MARKA' },
  { key: '206', value: 'BANCO MARTINELLI' },
  { key: '212', value: 'BANCO MATONE' },
  { key: '656', value: 'BANCO MATRIX' },
  { key: '243', value: 'BANCO MÁXIMA' },
  { key: '720', value: 'BANCO MAXINVEST' },
  { key: '388', value: 'BANCO MERCANTIL DE DESCONTOS' },
  { key: '392', value: 'BANCO MERCANTIL DE SAO PAULO' },
  { key: '389', value: 'BANCO MERCANTIL DO BRASIL' },
  { key: '008', value: 'BANCO MERIDIONAL DO BRASIL' },
  { key: '755', value: 'BANCO MERRILL LYNCH' },
  { key: '466', value: 'BANCO MITSUBISHI BRASILEIRO' },
  { key: '504', value: 'BANCO MULTIPLIC' },
  { key: '007', value: 'BANCO NAC DESENV. ECO. SOCIAL' },
  { key: '415', value: 'BANCO NACIONAL' },
  { key: '412', value: 'BANCO NACIONAL DA BAHIA' },
  { key: '420', value: 'BANCO NACIONAL DO NORTE' },
  { key: '733', value: 'BANCO NACOES' },
  { key: '165', value: 'BANCO NORCHEM' },
  { key: '424', value: 'BANCO NOROESTE' },
  { key: '247', value: 'BANCO OMEGA' },
  { key: '608', value: 'BANCO OPEN' },
  { key: '718', value: 'BANCO OPERADOR' },
  { key: '208', value: 'BANCO PACTUAL' },
  { key: '623', value: 'BANCO PANAMERICANO' },
  { key: '254', value: 'BANCO PARANA BANCO' },
  { key: '602', value: 'BANCO PATENTE' },
  { key: '611', value: 'BANCO PAULISTA' },
  { key: '650', value: 'BANCO PEBB' },
  { key: '613', value: 'BANCO PECUNIA' },
  { key: '264', value: 'BANCO PERFORMANCE' },
  { key: '277', value: 'BANCO PLANIBANC' },
  { key: '304', value: 'BANCO PONTUAL' },
  { key: '658', value: 'BANCO PORTO REAL' },
  { key: '724', value: 'BANCO PORTO SEGURO' },
  { key: '480', value: 'BANCO PORTUGUES DO ATLANTICO-BRASIL' },
  { key: '732', value: 'BANCO PREMIER' },
  { key: '719', value: 'BANCO PRIMUS' },
  { key: '638', value: 'BANCO PROSPER' },
  { key: '275', value: 'BANCO REAL' },
  { key: '633', value: 'BANCO REDIMENTO' },
  { key: '216', value: 'BANCO REGIONAL MALCON' },
  { key: '750', value: 'BANCO REPUBLIC NATIONAL OF NEW YORK' },
  { key: '453', value: 'BANCO RURAL' },
  { key: '204', value: 'BANCO S.R.L' },
  { key: '422', value: 'BANCO SAFRA' },
  { key: '033', value: 'BANCO SANTANDER' },
  { key: '702', value: 'BANCO SANTOS' },
  { key: '251', value: 'BANCO SAO JORGE' },
  { key: '250', value: 'BANCO SCHAHIN CURY' },
  { key: '643', value: 'BANCO SEGMENTO' },
  { key: '211', value: 'BANCO SISTEMA' },
  { key: '637', value: 'BANCO SOFISA' },
  { key: '366', value: 'BANCO SOGERAL' },
  { key: '347', value: 'BANCO SUDAMERIS BRASIL' },
  { key: '205', value: 'BANCO SUL AMERICA' },
  { key: '464', value: 'BANCO SUMITOMO BRASILEIRO' },
  { key: '657', value: 'BANCO TECNICORP' },
  { key: '618', value: 'BANCO TENDENCIA' },
  { key: '456', value: 'BANCO TOKIO' },
  { key: '634', value: 'BANCO TRIANGULO' },
  { key: '493', value: 'BANCO UNION' },
  { key: '736', value: 'BANCO UNITED' },
  { key: '726', value: 'BANCO UNIVERSAL' },
  { key: '610', value: 'BANCO VR' },
  { key: '261', value: 'BANCO VARIG' },
  { key: '715', value: 'BANCO VEGA' },
  { key: '711', value: 'BANCO VETOR' },
  { key: '655', value: 'BANCO VOTORANTIM' },
  { key: '629', value: 'BANCORP BANCO COML. E. DE INVESTMENTO' },
  { key: '489', value: 'BANESTO BANCO URUGAUAY' },
  { key: '744', value: 'BANK OF BOSTON' },
  { key: '184', value: 'BBA - CREDITANSTALT' },
  { key: '740', value: 'BCN BARCLAYS' },
  { key: '294', value: 'BCR - BANCO DE CREDITO REAL' },
  { key: '370', value: 'BEAL - BANCO EUROPEU PARA AMERICA LATINA' },
  { key: '601', value: 'BFC BANCO' },
  { key: '739', value: 'BGN' },
  { key: '125', value: 'BRASIL PLURAL BANCO MÚLTIPLO' },
  { key: '749', value: 'BRMSANTIL SA' },
  { key: '741', value: 'BRP' },
  { key: '218', value: 'BS2' },
  { key: '151', value: 'CAIXA ECONOMICA DO ESTADO DE SAO PAULO' },
  { key: '153', value: 'CAIXA ECONOMICA DO ESTADO DO R.G.SUL' },
  { key: '104', value: 'CAIXA ECONOMICA FEDERAL' },
  { key: '498', value: 'CENTRO HISPANO BANCO' },
  { key: '376', value: 'CHASE MANHATTAN BANK' },
  { key: '745', value: 'CITIBAN N.A.' },
  { key: '477', value: 'CITIBANK N.A' },
  { key: '175', value: 'CONTINENTAL BANCO' },
  { key: '085', value: 'COOPERATIVA CENTRAL DE CREDITO - AILOS' },
  { key: '210', value: 'DEUTSCH SUDAMERIKANICHE BANK AG' },
  { key: '487', value: 'DEUTSCHE BANK - BANCO ALEMAO' },
  { key: '751', value: 'DRESDNER BANK LATEINAMERIKA' },
  { key: '742', value: 'EQUATORIAL' },
  { key: '492', value: 'INTERNATIONALE NEDERLANDEN BANK N.V.' },
  { key: '472', value: 'LLOYDS BANK PLC' },
  { key: '738', value: 'MARADA' },
  { key: '323', value: 'MercadoPago.com' },
  { key: '255', value: 'MILBANCO' },
  { key: '746', value: 'MODAL SA' },
  { key: '148', value: 'MULTI BANCO' },
  { key: '260', value: 'Nu Pagamentos' },
  { key: '325', value: 'Órama DTVM' },
  { key: '290', value: 'PagSeguro Internet' },
  { key: '369', value: 'PONTUAL' },
  { key: '747', value: 'RABOBANK DO BRASIL' },
  { key: '748', value: 'SICREDI' },
  { key: '197', value: 'STONE PAGAMENTOS' },
  { key: '737', value: 'THECA' },
  { key: '409', value: 'UNIBANCO - UNIAO DOS BANCOS BRASILEIROS' },
  { key: '102', value: 'XP INVESTIMENTOS' }
]
